#!/bin/bash
set -x

# Variables de color
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # Sin color

# Archivo de log para registrar la salida de las migraciones.
LOGFILE="migraciones.log"

# Registra el inicio del proceso con la fecha.
echo "=== Inicio de migraciones: $(date) ===" >> "$LOGFILE"

# Función para ejecutar una migración, capturar la salida y registrar si se completó o no.
run_migration() {
  MIGRATION="$1"
  echo "=== Ejecutando migración: $MIGRATION ===" | tee -a "$LOGFILE"
  
  # Captura la salida y el código de salida del comando.
  output=$(vendor/bin/drush migrate:import "$MIGRATION" 2>&1)
  exit_status=$?
  
  # Registra la salida del comando.
  echo "$output" | tee -a "$LOGFILE"
  
  # Evalúa el código de salida y muestra el resultado, coloreando el mensaje de error en rojo.
  if [ $exit_status -eq 0 ]; then
    echo -e "${GREEN}Migración '$MIGRATION' completada exitosamente.${NC}" | tee -a "$LOGFILE"
  else
    echo -e "${RED}Migración '$MIGRATION' fallida.${NC}" | tee -a "$LOGFILE"
  fi
}

# Lista de migraciones a ejecutar
# run_migration "d7_node_complete:area"     
# run_migration "d7_node_complete:articulo_de_seccion"
# run_migration "d7_node_complete:blog"     
# run_migration "d7_node_complete:boletin_interno"
# run_migration "d7_node_complete:cartelera"
# run_migration "d7_node_complete:cifras_proteccion" 
# run_migration "d7_node_complete:commission_reports"
# run_migration "d7_node_complete:contacto_nacional"
# run_migration "d7_node_complete:convocatorias_talento_humano"  
# run_migration "d7_node_complete:dit_catalog"    
# run_migration "d7_node_complete:document" 
# run_migration "d7_node_complete:documentos_juridica"
# run_migration "d7_node_complete:encuesta_interna"  
# run_migration "d7_node_complete:enlace"   
# run_migration "d7_node_complete:estadisticas_institucionales"   
# run_migration "d7_node_complete:eventos_galeria"
# run_migration "d7_node_complete:event_calendar" 
# run_migration "d7_node_complete:forum"    
# run_migration "d7_node_complete:frase_de_la_semana" 
# run_migration "d7_node_complete:helpcenter_info"
# run_migration "d7_node_complete:institutional_stationery" 
# run_migration "d7_node_complete:isotope_example"
# run_migration "d7_node_complete:minutes_regional_strategic_commu"     
# run_migration "d7_node_complete:multimedia"     
run_migration "d7_node_complete:news"     
# run_migration "d7_node_complete:noticias_ejes"  
# run_migration "d7_node_complete:page"     
# run_migration "d7_node_complete:panel"    
# run_migration "d7_node_complete:persona"  
# run_migration "d7_node_complete:pieza_sgsi"     
# run_migration "d7_node_complete:poll"     
# run_migration "d7_node_complete:process_sige"   
# run_migration "d7_node_complete:promocionales_home" 
# run_migration "d7_node_complete:publicaciones_sindicato"  
# run_migration "d7_node_complete:webform"  
# run_migration "d7_node:area"  
# run_migration "d7_node:articulo_de_seccion"     
# run_migration "d7_node:blog"  
# run_migration "d7_node:boletin_interno"   
# run_migration "d7_node:cartelera"   
# run_migration "d7_node:cifras_proteccion" 
# run_migration "d7_node:commission_reports"
# run_migration "d7_node:contacto_nacional" 
# run_migration "d7_node:convocatorias_talento_humano"
# run_migration "d7_node:dit_catalog" 
# run_migration "d7_node:document"    
# run_migration "d7_node:documentos_juridica"     
# run_migration "d7_node:encuesta_interna"  
# run_migration "d7_node:enlace"
# run_migration "d7_node:estadisticas_institucionales"
# run_migration "d7_node:eventos_galeria"   
# run_migration "d7_node:event_calendar"    
# run_migration "d7_node:forum" 
# run_migration "d7_node:frase_de_la_semana"
# run_migration "d7_node:helpcenter_info"   
# run_migration "d7_node:institutional_stationery"
# run_migration "d7_node:isotope_example"   
# run_migration "d7_node:minutes_regional_strategic_commu" 
# run_migration "d7_node:multimedia"  
run_migration "d7_node:news"  
# run_migration "d7_node:noticias_ejes"     
# run_migration "d7_node:page"  
# run_migration "d7_node:panel" 
# run_migration "d7_node:persona"     
# run_migration "d7_node:pieza_sgsi"  
# run_migration "d7_node:poll"  
# run_migration "d7_node:process_sige"
# run_migration "d7_node:promocionales_home"
# run_migration "d7_node:publicaciones_sindicato"
# run_migration "d7_node:webform"
run_migration "d7_field_group:node:news"
# run_migration "d7_field_group:node:persona"
# run_migration "d7_field_group:node:document"
# run_migration "d7_field_group:node:page"
# run_migration "d7_field_group:node:process_sige"
# run_migration "d7_field_group:node:noticias_ejes"
# run_migration "d7_field_group:taxonomy_term:centro_de_ayuda"
# run_migration "d7_field_group:node:helpcenter_info"
# run_migration "d7_field_group:node:contacto_nacional"
# run_migration "d7_node_revision:area"     
# run_migration "d7_node_revision:articulo_de_seccion"
# run_migration "d7_node_revision:blog"     
# run_migration "d7_node_revision:boletin_interno"
# run_migration "d7_node_revision:cartelera"
# run_migration "d7_node_revision:cifras_proteccion" 
# run_migration "d7_node_revision:commission_reports"
# run_migration "d7_node_revision:contacto_nacional"
# run_migration "d7_node_revision:convocatorias_talento_humano"  
# run_migration "d7_node_revision:dit_catalog"    
# run_migration "d7_node_revision:document" 
# run_migration "d7_node_revision:documentos_juridica"
# run_migration "d7_node_revision:encuesta_interna"  
# run_migration "d7_node_revision:enlace"   
# run_migration "d7_node_revision:estadisticas_institucionales"   
# run_migration "d7_node_revision:eventos_galeria"
# run_migration "d7_node_revision:event_calendar" 
# run_migration "d7_node_revision:forum"    
# run_migration "d7_node_revision:frase_de_la_semana" 
# run_migration "d7_node_revision:helpcenter_info"
# run_migration "d7_node_revision:institutional_stationery" 
# run_migration "d7_node_revision:isotope_example"
# run_migration "d7_node_revision:minutes_regional_strategic_commu"     
# run_migration "d7_node_revision:multimedia"     
run_migration "d7_node_revision:news"     
# run_migration "d7_node_revision:noticias_ejes"  
# run_migration "d7_node_revision:page"     
# run_migration "d7_node_revision:panel"    
# run_migration "d7_node_revision:persona"  
# run_migration "d7_node_revision:pieza_sgsi"     
# run_migration "d7_node_revision:poll"     
# run_migration "d7_node_revision:process_sige"   
# run_migration "d7_node_revision:promocionales_home" 
# run_migration "d7_node_revision:publicaciones_sindicato"  
# run_migration "d7_node_revision:webform"
# run_migration "d7_url_alias"
# run_migration "d7_rdf_mapping"
# run_migration "statistics_node_counter"

# Registra el final del proceso.
echo "=== Fin de migraciones: $(date) ===" >> "$LOGFILE"
